notifications:
  email: false

language: node_js
node_js: 9
# cache:
#   directories:
#     - ~/.npm

branches:
  only:
  - master
  - /^greenkeeper/.*$/
  except:
    - /^v\d+\.\d+\.\d+$/

install: npm install

script:
- npm run build
- npm run test

before_deploy:
  - npm i -g semantic-release
  - npm i -g @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/npm @semantic-release/git @semantic-release/github

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx travis-deploy-once "npx semantic-release"


