notifications:
  email: false

language: node_js
node_js: 9
# cache:
#   directories:
#     - ~/.npm

branches:
  only:
  - master
  - /^greenkeeper/.*$/
  except:
    - /^v\d+\.\d+\.\d+$/

# before_install:
#     - npm install -g gulp-cli

install: npm install

script:
- npm run build
- npm run test

before_deploy:
    - npm install semantic-release
    - npm install @semantic-release/commit-analyzer
    - npm install @semantic-release/release-notes-generator
    - npm install @semantic-release/changelog
    - npm install @semantic-release/git
    - npm install @semantic-release/github
    - npm install @semantic-release/npm
    - npx semantic-release

deploy:
  provider: script
  skip_cleanup: true
  script:
    bash ./deploy.sh
