notifications:
  email: false

language: node_js
node_js: 9
cache:
  directories:
    - ~/.npm

branches:
  only:
  - master
  - /^greenkeeper/.*$/
  except:
    - /^v\d+\.\d+\.\d+$/

install: npm install

script:
- npm run build
- npm run test

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npm install -g travis-deploy-once
    - npx travis-deploy-once "npx semantic-release"
